"""Domain layer: pure entities, value objects, and processing state machine.

Imports standard library and packages/core ONLY.
"""

from packages.domain.entities import (
    AttachmentRef,
    Candidate,
    Checkpoint,
    Classification,
    ContextPackage,
    DraftRef,
    EmailAddress,
    EmailThread,
    Job,
    Mailbox,
    NormalizedMessage,
    OutboundReply,
    ProcessingEvent,
    RawMessage,
    RawThread,
    SentRef,
    Subscription,
    SyncResult,
    ThreadRef,
)
from packages.domain.rules import (
    EmailContext,
    Rule,
    RuleAction,
    RuleEngine,
)
from packages.domain.state_machine import (
    TRANSITIONS,
    IllegalStateTransitionError,
    JobState,
    transition_job,
    validate_transition,
)
from packages.domain.taxonomy import (
    CANONICAL_CATEGORIES,
    CANONICAL_DEFINITIONS,
    NO_REPLY_CATEGORIES,
    RETRIEVAL_CATEGORIES,
    Category,
    CategoryDefinition,
    TaxonomyRegistry,
    get_category_definition,
    get_default_registry,
    is_valid_category,
    normalize_category,
    validate_category,
)

__all__ = [
    "CANONICAL_CATEGORIES",
    "CANONICAL_DEFINITIONS",
    "NO_REPLY_CATEGORIES",
    "RETRIEVAL_CATEGORIES",
    "TRANSITIONS",
    "AttachmentRef",
    "Candidate",
    "Category",
    "CategoryDefinition",
    "Checkpoint",
    "Classification",
    "ContextPackage",
    "DraftRef",
    "EmailAddress",
    "EmailContext",
    "EmailThread",
    "IllegalStateTransitionError",
    "Job",
    "JobState",
    "Mailbox",
    "NormalizedMessage",
    "OutboundReply",
    "ProcessingEvent",
    "RawMessage",
    "RawThread",
    "Rule",
    "RuleAction",
    "RuleEngine",
    "SentRef",
    "Subscription",
    "SyncResult",
    "TaxonomyRegistry",
    "ThreadRef",
    "get_category_definition",
    "get_default_registry",
    "is_valid_category",
    "normalize_category",
    "transition_job",
    "validate_category",
    "validate_transition",
]

